version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: omni
      POSTGRES_USER: omni
      TZ: 'GMT-3'
      PGTZ: 'GMT-3'
    ports:
      - 6543:5432
    networks:
      - local-network
networks:
  local-network:
    driver: bridge
