version: '3.9'

services:
  perroute-api:
    container_name: perroute-api
    build:
      context: ..
      dockerfile: crates/perroute-api/Dockerfile
    volumes:
      - /tmp/app:/var/log/app
    ports:
      - '8080:8080'
    env_file:
      - ../.env
      - ../.env.docker
    depends_on:
      - perroute_postgres
