version: '3.9'

services:
  omni_message_postgres:
    container_name: omni_message_postgres
    image: postgres:latest
    restart: always
    env_file:
      - ../.env.docker
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
