version: '3.9'

services:
  perroute-backoffice-api:
    container_name: perroute-backoffice-api
    build:
      context: ..
      dockerfile: crates/perroute-backoffice-api/Dockerfile
    volumes:
      - /tmp/app:/var/log/app
    ports:
      - '8080:8080'
    env_file:
      - ../.env
      - ../.env.docker
    depends_on:
      - perroute-rabbitmq
      - perroute_message_postgres
