server:
  port: 8080
  host: 127.0.0.1
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  database_name: "postgres"
  require_ssl: false
  pool:
    max_connection: 10
    max_lifetime: 20
    idle_timeout: 20
    acquire_timeout: 2
  migration:
    enabled: false
rabbitmq:
  uri: "amqp://admin:admin@localhost:5672"
template_storage:
  bucket_name: "template-storage"
otlp:
  endpoint: "http://localhost:4317"
  enabled: false
